### ISSUE TITLE
So what do I type for my partition?

### ISSUE THREAD

**Issue by IndustrialOne** [nneonneo/ntfsrecover#1]
python ntfsrecover.py /dev/diskX --save-mft mft

How do I know which disk it is? I'm hoping the disk doesn't mean physical disk because it's like the 10th partition on the second disk.

**Comment by nneonneo** [comment]
It should work with a partition. I believe fdisk should be able to tell you
which partition it is.

**Comment by IndustrialOne** [comment]
fdisk is not working on Windows 7 here.

**Comment by nneonneo** [comment]
Thank you for your bug report. I just tested it on Windows and fixed a few bugs (https://github.com/nneonneo/ntfsrecover/commit/a7833a6b12f0b6336b35279e29a36efc92582a23), so now it should work for recovering data on Windows. Use `\\.\HarddiskNPartitionM` as the disk, where `N` is 0-indexed and `M` is 1-indexed.

To get the indices, you can use `diskpart`. Use `list disk` to get a list of disks, `select disk N` to select a disk, and `list partition` to get a list of partitions on that dist.

**Comment by nneonneo** [comment]
Fixed in a7833a6b12f0b6336b35279e29a36efc92582a23.
