### ISSUE TITLE
not a iisue but a comment

### ISSUE THREAD

**Issue by ghost** [nneonneo/ntfsrecover#2]
Could you possibly  write testcase for the script.

**Comment by nneonneo** [comment]
I don't really have a realistic NTFS image to use as a testcase. If you'd like to contribute one that'd be really helpful.

**Comment by ghost** [comment]
I wish I had one. Your project could very  useful in the it sector for data recovery.

**Comment by nneonneo** [comment]
That's the goal. I could provide a stock NTFS file for a testcase, but that's much less interesting than a realistically corrupted one (and those I do not have).

Closing for now - but thanks for the suggestion.
