### ISSUE TITLE
Files are showing while running the save-mft(Verbose) command but not showing in the recovered folder when running the --pattern command.

### ISSUE THREAD

**Issue by r3h3mm** [nneonneo/ntfsrecover#4]
![7808b289-fe0b-48ea-96fc-12336f83f7c5-1](https://user-images.githubusercontent.com/56667806/77923429-1207a680-72c0-11ea-9fb6-532624f8503c.JPG)

![0391a46e-82ba-4dbd-9790-d8a89db42b30](https://user-images.githubusercontent.com/56667806/77923049-7bd38080-72bf-11ea-83fb-fdc7a829f0c1.JPG)

PLEASE HELP

**Comment by nneonneo** [comment]
Try using `"*.jpg"` (using double quotes instead of single quotes), since Windows `cmd.exe` doesn't interpret single quotes?

**Comment by r3h3mm** [comment]
Thank you!!

**Comment by nneonneo** [comment]
Thanks for the report - I updated the guidance in the README to avoid single quotes.

**Comment by r3h3mm** [comment]
Thank you for responding so quickly.
