### ISSUE TITLE
I have an issue with the mac recovery, throws an error while running the --save-mft command that the disk is not an NTFS but the diskutil shows that the disk is NTFS!

### ISSUE THREAD

**Issue by r3h3mm** [nneonneo/ntfsrecover#5]
![Screen Shot 2020-03-30 at 11 03 07 PM](https://user-images.githubusercontent.com/56667806/77943616-2311e100-72db-11ea-866d-278de11efbfa.png)
![Screen Shot 2020-03-30 at 11 03 42 PM](https://user-images.githubusercontent.com/56667806/77943628-260cd180-72db-11ea-835d-7dca70fc2356.png)
Please HELP
Am using the same pendrive which i used in the windows laptop!

**Comment by nneonneo** [comment]
You have to use the partition label `/dev/disk4s1` (`/dev/disk4` refers to the whole disk).

**Comment by r3h3mm** [comment]
Worked! Thanks again
